name: Just Run Autogpt
on:
  workflow_dispatch :   #only run when requested
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
    - name: Print GitHub context
      run: echo GITHUB_CONTEXT: ${{ toJson(github) }}
    - uses: meta-introspector/checkout@v3
    - name: Checkout repository
      uses: actions/checkout@master
      with:
        submodules: 'true'        
    - name: Run autogpt in docker with mock openai server
      run: docker-compose up --no-build
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
        GITHUB_REPO: "meta-introspector/call-auto-gpt"